# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Simpledeploy < Formula
  desc "Lightweight deployment manager for Docker Compose apps"
  homepage "https://github.com/vazra/simpledeploy"
  version "1.4.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vazra/simpledeploy/releases/download/v1.4.1/simpledeploy_1.4.1_darwin_amd64.tar.gz"
      sha256 "990d7f806cbe9aebff5e683daf3189b49970815f2883f3351ef682ca8a792e26"

      define_method(:install) do
        bin.install "simpledeploy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vazra/simpledeploy/releases/download/v1.4.1/simpledeploy_1.4.1_darwin_arm64.tar.gz"
      sha256 "598c23c919ebcedc78eeb05506208f613ef56d6d04f8f3d717186dd212983993"

      define_method(:install) do
        bin.install "simpledeploy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vazra/simpledeploy/releases/download/v1.4.1/simpledeploy_1.4.1_linux_amd64.tar.gz"
      sha256 "ddae4a5163609318ebc818c0f4825c8a43cc219d624ba55b7a4489a2e50a1fc6"
      define_method(:install) do
        bin.install "simpledeploy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vazra/simpledeploy/releases/download/v1.4.1/simpledeploy_1.4.1_linux_arm64.tar.gz"
      sha256 "0a9a61974e640d604236f3fa92a5b11a70589e2ab833cb62fe8e4e810a0c1fcb"
      define_method(:install) do
        bin.install "simpledeploy"
      end
    end
  end

  test do
    system "#{bin}/simpledeploy", "version"
  end
end
