# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Simpledeploy < Formula
  desc "Lightweight deployment manager for Docker Compose apps"
  homepage "https://github.com/vazra/simpledeploy"
  version "1.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vazra/simpledeploy/releases/download/v1.4.0/simpledeploy_1.4.0_darwin_amd64.tar.gz"
      sha256 "f612d41d374102651f0e798d61035fa6d63e1c74b47ca37f706b31adc5749fc6"

      define_method(:install) do
        bin.install "simpledeploy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vazra/simpledeploy/releases/download/v1.4.0/simpledeploy_1.4.0_darwin_arm64.tar.gz"
      sha256 "6e89504e09d225b08be57200c348199ee1a567ec243eaa552f9581970ebc7533"

      define_method(:install) do
        bin.install "simpledeploy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vazra/simpledeploy/releases/download/v1.4.0/simpledeploy_1.4.0_linux_amd64.tar.gz"
      sha256 "a32b23fc92c60d82e343b271d26aa0a16746e1008b35205bc658c2b6ff6027db"
      define_method(:install) do
        bin.install "simpledeploy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vazra/simpledeploy/releases/download/v1.4.0/simpledeploy_1.4.0_linux_arm64.tar.gz"
      sha256 "a2c110be37244c4aee36da8cfe764efd6744309b8b5d903d0a8485728231c045"
      define_method(:install) do
        bin.install "simpledeploy"
      end
    end
  end

  test do
    system "#{bin}/simpledeploy", "version"
  end
end
