# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Simpledeploy < Formula
  desc "Lightweight deployment manager for Docker Compose apps"
  homepage "https://github.com/vazra/simpledeploy"
  version "1.4.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vazra/simpledeploy/releases/download/v1.4.4/simpledeploy_1.4.4_darwin_amd64.tar.gz"
      sha256 "0b2a020255560da9fce2619750b638c0c8f7ae1c68541f7536ac9d465dd90499"

      define_method(:install) do
        bin.install "simpledeploy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vazra/simpledeploy/releases/download/v1.4.4/simpledeploy_1.4.4_darwin_arm64.tar.gz"
      sha256 "67343afd462414addf9f00f679713ac39a5db1c5d6d30cdb3109f7f751565b73"

      define_method(:install) do
        bin.install "simpledeploy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vazra/simpledeploy/releases/download/v1.4.4/simpledeploy_1.4.4_linux_amd64.tar.gz"
      sha256 "5d91dac7e631d0167801364b89af5a2e4db402a3c5df46d6c176c3f827ddce6f"
      define_method(:install) do
        bin.install "simpledeploy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vazra/simpledeploy/releases/download/v1.4.4/simpledeploy_1.4.4_linux_arm64.tar.gz"
      sha256 "f6af65bfff688e6c1171d6788c6fa13c92b75f56c917bdf0e23f186d1f39dc3c"
      define_method(:install) do
        bin.install "simpledeploy"
      end
    end
  end

  test do
    system "#{bin}/simpledeploy", "version"
  end
end
